name: freehand
description: "A Flutter port of perfect-freehand drawing logic, based on the Tldraw fork for smoother strokes."
version: 0.0.1
homepage: https://github.com/keyur2maru/freehand

environment:
  sdk: ^3.2.3
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - perfect-freehand
  - freehand
  - drawing
  - tldraw
  - sketching